---
- name: List clusters in a datacenter
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars.yml
 
  tasks:
    - name: Provide information about vCenter datacenters
      community.vmware.vmware_cluster_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: '{{ vcenter_datacenter }}'
      delegate_to: localhost
      register: cluster_info
    - name: Output cluster names
      debug:
        msg: "{{ item }}"
      loop: "{{ cluster_info.clusters.keys() | list }}"